# Branch Protection Configuration
# This file defines branch protection rules for the repository
# Apply via GitHub CLI: gh api repos/:owner/:repo/branches/main/protection --method PUT --input .github/branch-protection.yml

required_status_checks:
    strict: true
    contexts:
        - 'security-scan'
        - 'lint-and-typecheck'
        - 'test (18.20.4, ubuntu-latest)'
        - 'test (20.17.0, ubuntu-latest)'
        - 'test (22.17.1, ubuntu-latest)'
        - 'build-and-push'
        - 'performance-check'

enforce_admins: false

required_pull_request_reviews:
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    required_approving_review_count: 1
    require_last_push_approval: false

restrictions:
    users: []
    teams: []
    apps: []

required_linear_history: false
allow_force_pushes: false
allow_deletions: false
block_creations: false
required_conversation_resolution: true
lock_branch: false
allow_fork_syncing: true
