version: 2
updates:
    # Game Development Dependencies
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '06:00'
          timezone: 'UTC'
      open-pull-requests-limit: 8
      labels:
          - 'dependencies'
          - 'game-development'
      commit-message:
          prefix: 'deps'
          include: 'scope'
      groups:
          # Core Game Development
          game-engine:
              patterns:
                  - 'phaser*'
                  - 'lz-string*'

          # TypeScript and Build Tools
          typescript-tools:
              patterns:
                  - 'typescript*'
                  - '@typescript-eslint/*'
                  - '@types/*'
                  - 'vite*'
                  - '@vitejs/*'

          # Testing Framework
          testing-tools:
              patterns:
                  - 'vitest*'
                  - '@vitest/*'
                  - 'jsdom*'
                  - '@playwright/*'
                  - 'playwright*'

          # Code Quality
          code-quality:
              patterns:
                  - 'eslint*'
                  - 'eslint-*'
                  - 'prettier*'
                  - 'husky*'
                  - 'lint-staged*'

          # Asset Processing
          asset-tools:
              patterns:
                  - 'sharp*'
                  - 'canvas*'
                  - 'maxrects-packer*'

    # GitHub Actions Updates
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '06:00'
          timezone: 'UTC'
      open-pull-requests-limit: 3
      labels:
          - 'github-actions'
          - 'ci-cd'
      commit-message:
          prefix: 'ci'
          include: 'scope'
