# Game CI Pipeline 2025
name: Game CI Pipeline 2025

permissions:
    contents: read
    packages: write
    security-events: write
    id-token: write

on:
    pull_request:
        branches: [main, develop]
    push:
        branches: [main, develop]

jobs:
    security-scan:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.17.1'
                  cache: 'npm'

            - name: Install dependencies
              run: |
                  npm ci --prefer-offline --no-audit --no-fund
                  npm ls --depth=0

            - name: Run security linting
              run: npm run lint

            - name: Check for known vulnerabilities
              run: npm audit --audit-level moderate

            - name: Enhanced dependency security check
              run: npx better-npm-audit audit --level moderate

    lint-and-typecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.17.1'
                  cache: 'npm'

            - name: Install dependencies
              run: |
                  npm ci --prefer-offline --no-audit --no-fund
                  npm ls --depth=0

            - name: Debug Environment
              run: |
                  echo "Node version: $(node --version)"
                  echo "NPM version: $(npm --version)"
                  echo "OS: $(cat /etc/os-release | grep PRETTY_NAME)"
                  echo "Current directory: $(pwd)"
                  echo "Project files:"
                  ls -la

            - name: Run TypeScript check
              run: npm run typecheck

            - name: Run linting
              run: npm run lint

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        strategy:
            matrix:
                node-version: [22, 23]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: |
                  npm ci --prefer-offline --no-audit --no-fund
                  npm ls --depth=0

            - name: Run tests
              run: npm run test:run
              timeout-minutes: 5

            - name: Upload coverage artifacts
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: coverage-${{ matrix.node-version }}
                  path: coverage/

    build-and-push:
        runs-on: ubuntu-latest
        needs: [lint-and-typecheck, test, security-scan]
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.17.1'
                  cache: 'npm'

            - name: Install dependencies
              run: |
                  # Force rebuild Sharp for Linux asset pipeline
                  npm ci --prefer-offline --no-audit --no-fund
                  npm rebuild sharp
                  npm ls sharp

            - name: Build application
              run: |
                  echo "Starting build process..."
                  npm run build
                  echo "Build completed. Checking outputs:"
                  ls -la dist/
                  du -sh dist/

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts
                  path: dist/

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=sha

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: false # Temporarily disable GHCR push until permissions resolved
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

    performance-check:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.17.1'
                  cache: 'npm'

            - name: Install dependencies
              run: |
                  npm ci --prefer-offline --no-audit --no-fund
                  npm rebuild sharp

            - name: Build and check bundle size
              run: |
                  npm run build
                  echo "Build completed successfully"

            - name: Run performance check script
              run: npm run performance:check
