# Game CI Pipeline 2025
name: Game CI Pipeline 2025
on:
    pull_request:
        branches: [main, develop]
    push:
        branches: [main, develop]

jobs:
    security-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  languages: javascript, typescript

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3

    lint-and-typecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run TypeScript check
              run: npm run typecheck

            - name: Run linting
              run: npm run lint

    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22, 23]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run tests with coverage
              run: npm run test:coverage

            - name: Upload coverage artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-${{ matrix.node-version }}
                  path: coverage/

    build-and-push:
        runs-on: ubuntu-latest
        needs: [lint-and-typecheck, test, security-scan]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build application
              run: npm run build

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts
                  path: dist/

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=sha

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

    performance-check:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run performance tests
              run: npm run test:e2e

            - name: Check bundle size
              run: |
                  npm run build
                  BUNDLE_SIZE=$(du -sh dist/ | cut -f1)
                  echo "Bundle size: $BUNDLE_SIZE"
                  # Check if bundle is under 5MB for MVP
                  if [ $(du -s dist/ | cut -f1) -gt 5120 ]; then
                    echo "Bundle size exceeds 5MB limit"
                    exit 1
                  fi
