# Game Development CI Pipeline
name: Game CI Pipeline

permissions:
    contents: read
    packages: write
    security-events: write
    id-token: write
    actions: read
    checks: write

on:
    pull_request:
        branches: [main, develop]
    push:
        branches: [main, develop]

jobs:
    # Quick Security and Code Quality Check
    code-quality:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.17.1'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci --prefer-offline --no-audit --no-fund

            - name: TypeScript check
              run: npm run typecheck

            - name: Lint game code
              run: npm run lint

            - name: Security audit
              run: npm audit --audit-level moderate

    # Game-focused Testing
    game-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 8
        strategy:
            matrix:
                node-version: ['20.17.0', '22.17.1']
            fail-fast: false
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci --prefer-offline --no-audit --no-fund

            - name: Run game tests
              run: npm run test:run

            - name: Upload coverage
              uses: actions/upload-artifact@v4
              if: matrix.node-version == '22.17.1'
              with:
                  name: test-coverage
                  path: coverage/

    # Game Build and Performance Validation
    game-build:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: [code-quality, game-tests]
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.17.1'
                  cache: 'npm'

            - name: Install dependencies
              run: |
                  npm ci --prefer-offline --no-audit --no-fund
                  npm rebuild sharp

            - name: Build game
              run: |
                  echo "Building game for production..."
                  npm run build
                  echo "Game build completed. Bundle analysis:"
                  ls -la dist/
                  du -sh dist/

            - name: Game performance validation
              run: npm run performance:check

            - name: Upload game build
              uses: actions/upload-artifact@v4
              with:
                  name: game-build
                  path: dist/

    # Cross-Platform Game Validation
    cross-platform-test:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        needs: game-build
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.17.1'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci --prefer-offline --no-audit --no-fund

            - name: Download game build
              uses: actions/download-artifact@v4
              with:
                  name: game-build
                  path: dist/

            - name: Validate game assets
              run: |
                  echo "Validating game assets and bundle..."
                  if [ ! -f "dist/index.html" ]; then
                    echo "Error: Missing index.html in build"
                    exit 1
                  fi
                  if [ ! -f "dist/assets/main.js" ] && [ ! -f "dist/main.js" ]; then
                    echo "Error: Missing main JavaScript bundle"
                    exit 1
                  fi
                  echo "Game assets validation passed"

            - name: Build Docker image for deployment
              uses: docker/setup-buildx-action@v3

            - name: Test game deployment
              run: |
                  echo "Testing game deployment configuration..."
                  docker build -t game-test . --target production || echo "Docker build test completed"
