# Production Deployment
name: Deploy to Production
on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build application
              run: npm run build

            - name: Generate build info
              run: node scripts/build-info.js

            - name: Blue-green deployment
              run: |
                  echo "Starting blue-green deployment..."
                  node scripts/deploy.js --environment=production

            - name: Health check
              run: |
                  echo "Performing production health check..."
                  # Add production health check logic
                  # curl -f https://play.neweden.game/api/health || exit 1

            - name: Notify production deployment
              run: |
                  echo "Production deployment completed successfully!"
                  echo "URL: https://play.neweden.game"
