# Staging Deployment
name: Deploy to Staging

permissions:
    contents: read
    packages: write

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build application
              run: npm run build

            - name: Generate build info
              run: node scripts/build-info.js

            - name: Deploy to staging
              run: |
                  echo "Deploying to staging environment..."
                  # Add your staging deployment logic here
                  # For example: deploy to Vercel, Netlify, or custom server

            - name: Health check
              run: |
                  echo "Performing health check..."
                  # Add health check logic here
                  # curl -f https://staging.neweden.game/api/health || exit 1

            - name: Notify deployment
              run: |
                  echo "Staging deployment completed successfully!"
                  echo "URL: https://staging.neweden.game"
