# Advanced Performance Monitoring
name: Performance Monitoring

permissions:
    contents: read
    packages: read

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        - cron: '0 2 * * *' # Daily at 2 AM

jobs:
    performance-advanced:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                device-profile:
                    - { name: 'low-tier', cpu: 2, memory: '4GB' }
                    - { name: 'mid-tier', cpu: 4, memory: '8GB' }
                    - { name: 'high-tier', cpu: 8, memory: '16GB' }
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build application
              run: npm run build

            - name: Run FPS Benchmarks
              run: |
                  # Install Playwright browsers if not cached
                  npx playwright install chromium --with-deps
                  # Run performance tests with CI-optimized settings  
                  npm run test:performance
              env:
                  CI: true

            - name: Check Performance Regression
              run: node tools/development/performance-check.js

            - name: Upload performance results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: performance-results-${{ matrix.device-profile.name }}
                  path: test-results/

            - name: Check for microfreezes
              run: |
                  echo "Microfreeze detection implemented in performance tests"
                  echo "Results available in performance test artifacts"
